apiVersion: v1
kind: Pod
metadata:
  name: cassandra-client
  namespace: default
spec:
  containers:
    - name: kafka
      image: cassandra:3.11.3
      command:
        - sh
        - -c
        - "exec tail -f /dev/null"
