apiVersion: batch/v1
kind: Job
metadata:
  name: flink-twitter-geo-app
spec:
  template:
    spec:
      containers:
      - name: flink-twitter-geo-app
        image: krinart/flink_pipeline
        env:
        - name: FLINK_APP_MAIN_CLASS
          value: flink_pipeline.TwitterGeoApp
      restartPolicy: Never
  backoffLimit: 0

