apiVersion: batch/v1
kind: Job
metadata:
  name: twitter-source-kafka
spec:
  template:
    spec:
      containers:
      - name: twitter-source
        image: gcr.io/pragmatic-zoo-253123/twitter_source
        args: ["TwitterSourceAppKafka"]
        env:
        - name: CONSUMER_KEY
          valueFrom:
            secretKeyRef:
              name: twitter-auth
              key: CONSUMER_KEY
        - name: CONSUMER_SECRET
          valueFrom:
            secretKeyRef:
              name: twitter-auth
              key: CONSUMER_SECRET
        - name: TOKEN
          valueFrom:
            secretKeyRef:
              name: twitter-auth
              key: TOKEN
        - name: TOKEN_SECRET
          valueFrom:
            secretKeyRef:
              name: twitter-auth
              key: TOKEN_SECRET
      restartPolicy: Never
  backoffLimit: 0
